### ISSUE TITLE
void devera_LancarIllegalArgumentException_QuandoNumeroContatoInvalido()

### ISSUE THREAD

**Issue by hamadecd** [cami-la/unit_testing_JUnit5#1]
Na classe AlunoServiceTest.java acho que o nome do método deveria ser: devera_LancarIllegal**State**Exception_QuandoNumeroContatoInvalido() ou mudar o código trocando IllegalStateException por IllegalArgumentException por exemplo, aí teria que mudar também na classe AlunoService.java

[Link para referência](https://docs.oracle.com/cd/B10501_01/appdev.920/a96121/im_exceptions.htm)

**Comment by cami-la** [comment]
Oi, amigo. Tudo bem? (:

Note que as implementações tanto do método a ser testado quanto do método de teste estão lançando uma **IllegalArgumentException**. 
Na verdade, a declaração do nome do método de teste que escrevi errado, trocando **IllegalArgumentException** por **IllegalArgumentException**.

```java
public Aluno novoAluno(String nome, String numeroContato) {
		if(!validaNumero(numeroContato)) {
			throw new IllegalStateException(String.format("Número inválido [%s]", numeroContato));
		}
		Aluno aluno = new Aluno();
		aluno.setId(new Random().nextLong());
		aluno.setNome(nome);
		aluno.setNumeroContato(numeroContato);
		return aluno;
	}
```

```java
@Test
	void devera_LancarIllegalArgumentException_QuandoNumeroContatoInvalido() {
		//given
		String nomeAluno = "Camila";
		String numeroContato = "87382";
		
		//when
		//then
		AlunoService alunoService = new AlunoService();
		IllegalStateException actualException = Assertions.assertThrows(IllegalStateException.class,
				() -> alunoService.novoAluno(nomeAluno, numeroContato));
		
		String expectedMessage = String.format("Número inválido [%s]", numeroContato);
		
		Assertions.assertEquals(expectedMessage, actualException.getMessage());		
	}
```

De qualquer forma, muito obrigada pela observação, **irei corrir o nome do método de teste!** (:

**Comment by hamadecd** [comment]
Oi Camila, vou bem obrigado. E Você? Aproveitando pra dizer que gosto muito das suas aulas na DIO.
Só pra ficar claro então pra mim, por favor. O que falta então é mudar o nome do método para que lance uma IllegalStateException? Na resposta acho que copiou o nome igual.

Muito obrigado, tento sempre aprender com seus exemplos.

**Comment by cami-la** [comment]
Foi ótima a sua observação!

O nome do método não interfere em nada na implementação/execução do método.

Precisamos deixar o nome coerente para que quando outro programador pegar no nosso código, ele entender do que se trata.
A implementação está correta, com a IllegalStateException.

Ainda não tive tempo de parar para consertar, então, copiei o mesmo método pra você ver a implementação como está.

E muito obrigada pelo feedback, viu? Precisando estou à disposição. 😊
